# Generated by Django 4.1.2 on 2022-10-25 21:14
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_resources'),
    ]

    operations = [
     migrations.AlterField(
            model_name='Resources',
            name='author',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='Resources',
            name='title',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
